import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "./providers/QueryProvider";
import { UserInfo } from "@/components/UserInfo";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <div className="min-h-screen flex flex-col">
            <header className="border-b border-gray-200 bg-white">
              <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex justify-between items-center h-16">
                  <Link
                    href="/"
                    className="text-xl font-bold text-gray-900 hover:text-blue-600 transition-colors"
                  >
                    BIGS App
                  </Link>
                  <nav className="flex items-center gap-6">
                    <Link
                      href="/boards"
                      className="text-sm font-medium text-gray-700 hover:text-gray-900 transition-colors"
                    >
                      게시판
                    </Link>
                    <UserInfo />
                  </nav>
                </div>
              </div>
            </header>

            <main className="flex-1">{children}</main>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
